spring.application.name=ConectaLar

spring.output.ansi.enabled=always
# Define path raiz do endpoint
# http://localhost:8080/raiz_do_endpoint/algumacoisa
server.servlet.context-path=/raiz_do_endpoint

spring.profiles.active=${APP_ENVIRONMENT:test}
#spring.profiles.active=test
#spring.profiles.active=prod

# Definição de Porta
# Procura uma variavel de ambiente SERVER_PORT. Caso não exista utiliza
# a porta 8080 como default.
server.port=${SERVER_PORT:8080}

